name: Veira
version: '${project.version}'
main: kabl.veira.Veira
api-version: '1.20'
authors: [ Kabl ]
description: Funny custom meme plugin

permissions :
  permission.node:
    description: "This is a permission node"
    default: op

commands:
  nword:
    description: Zeigt wie oft ein Spieler das N-Wort geschrieben hat
    usage: /<command>

  playtime:
    description: Zeigt Spielzeit von Spielern an
    usage: /<command>
    aliases:
      - spielzeit

  daily:
    description: T채gliche Aufgaben
    usage: /<command>
    aliases:
      - quest
      - quests

  aktivierungsmodussteuerungsmodul:
    description: Zuf채lliger Effekt (Achtung kann literally gamebreaking sein)
    usage: /<command> starten

  deposit:
    description: Diamanten einzahlen
    usage: /<command> <amount>

  withdraw:
    description: Diamanten auszahlen
    usage: /<command> <amount>

  pay:
    description: Zahle einem Spieler Diamanten
    usage: /<command> <target> <amount>

  info:
    description: Zeigt informationen 체ber den Spieler
    usage: /<command> <name>
    aliases:
      - who
      - wer
      - informationsbeschaffung

  gamble:
    description: Gl체cksspiel
    usage: /<command>

  spawn:
    description: Teleportiert dich an den Spawn, 5 Minuten Cooldown
    usage: /<command>

  setspawn:
    description: Setzt world-spawn
    usage: /<command>
    permission: permission.node
    permission-message: You do not have permission to use this command.

  schizo:
    description: Die stimmen werden lauter
    usage: /<command>