name: Veira
version: '${project.version}'
main: kabl.veira.Veira
api-version: 1.20
authors: [ Kabl ]
description: Funny custom meme plugin

commands:
  nword:
    description: Zeigt wie oft ein Spieler das N-Wort geschrieben hat
    usage: /<command>

  playtime:
    description: Zeigt Spielzeit von Spielern an
    usage: /<command>
    aliases:
      - spielzeit

  daily:
    description: Tägliche Aufgaben
    usage: /<command>
    aliases:
      - quest
      - quests

  aktivierungsmodussteuerungsmodul:
    description: Zufälliger Effekt (Achtung kann literally gamebreaking sein)
    usage: /<command> starten

  deposit:
    description: todo
    usage: /<command> <amount>

  withdraw:
    description: todo
    usage: /<command> <amount>

  info:
    description: todo
    usage: /<command> <name>
    aliases:
      - who
      - wer
      - informationsbeschaffung

  gamble:
    description: todo
    usage: /<command>